CREATE TABLE `kakao_pay`.`TBL_BLESSING` (
  `SEQ` INT NOT NULL AUTO_INCREMENT COMMENT '유효번호',
  `BLESSER_ID` VARCHAR(45) NOT NULL COMMENT '뿌린이 ID',
  `ROOM_ID` VARCHAR(45) NOT NULL COMMENT '대화방 ID',
  `AMOUNT` INT NOT NULL COMMENT '뿌린 총 금액',
  `MAX_RECEIVER_COUNT` INT NOT NULL COMMENT '받아갈 대상자 숫자',
  `BLESSING_DATE` DATE NOT NULL COMMENT '뿌린일시',
  `TOKEN` VARCHAR(3) NOT NULL COMMENT '3자리 유니크한 토큰',
  PRIMARY KEY (`SEQ`))
COMMENT = '뿌리기';
